#!/usr/bin/env python

DESCRIPTION = """
GraphProt:

Explicit Decomposition with Neighborhood (EDeN) utility program for 
sequence-based modeling of binding preferences of RNA-binding proteins.
"""

EPILOG = """
Author: Daniel Maticzka
Copyright: 2015
License: GPL
Maintainer: Daniel Maticzka
Email: maticzkd@informatik.uni-freiburg.de
Status: Development

Please cite:

    Daniel Maticzka, Sita J. Lange, Fabrizio Costa, Rolf Backofen
    GraphProt: modeling binding preferences of RNA-binding proteins
    Genome Biology, 2014, 15(1), R17
"""

from eden.model_base import *

class ModelInitializer(ModelInitializerBase):

    def load_data(self, input_file):
        from eden.converter.fasta import fasta_to_sequence
        seqs = fasta_to_sequence(input_file)
        return seqs

    def load_positive_data(self, args):
        return self.load_data(args.positive_input_file)

    def load_negative_data(self, args):
        return self.load_data(args.negative_input_file)

    def vectorizer_init(self, n_iter):
        vectorizer = Vectorizer()
        vectorizer_parameters = {'complexity': [2, 3, 4, 5, 6]}
        return vectorizer, vectorizer_parameters

    def add_arguments(self, parser):
        parser.add_argument('--version', action='version', version='0.1')
        return parser

    def add_arguments_fit(self, parser):
        parser.add_argument("-i", "--bound-file",
                            dest="positive_input_file",
                            help="Path to FASTA file containing sequences of bound sites.",
                            required=True)
        parser.add_argument("-u", "--unbound-file",
                            dest="negative_input_file",
                            help="Path to FASTA file containing sequences on unbound sites.",
                            required=True)
        return parser

    def add_arguments_estimate(self, parser):
        return self.add_arguments_fit(parser)


if __name__ == "__main__":
    model_initializer = ModelInitializer()
    main_script(model_initializer=model_initializer,
                description=DESCRIPTION,
                epilog=EPILOG,
                prog_name=os.path.basename(__file__),
                logger=logging.getLogger())